@echo off
echo Copiando 
copy d:\nibbot\client\src\components\admin\abmmenu.js
copy d:\nibbot\client\src\components\admin\abmmenu.js
copy d:\nibbot\client\src\components\admin\cliente.js
copy d:\nibbot\client\src\components\admin\direccion.js
copy d:\nibbot\client\src\components\admin\formCliente.js
copy d:\nibbot\client\src\components\admin\formdireccion.js
copy d:\nibbot\client\src\components\admin\formMateriaprima.js
copy d:\nibbot\client\src\components\admin\formProducto.js
copy d:\nibbot\client\src\components\admin\formProductoLang.js
copy d:\nibbot\client\src\components\admin\formTabla.js
copy d:\nibbot\client\src\components\admin\formUsuario.js
copy d:\nibbot\client\src\components\admin\materiaprima.js
copy d:\nibbot\client\src\components\admin\prodMp.js
copy d:\nibbot\client\src\components\admin\producto.js
copy d:\nibbot\client\src\components\admin\productoLang.js
copy d:\nibbot\client\src\components\admin\tablas.js
copy d:\nibbot\client\src\components\admin\usuario.js
copy d:\nibbot\client\src\components\admin\usuariomenu.js
pause